<?php
    /** @var $block \Codilar\ProShopping\Block\Contactblock */

    /** @var \Codilar\ProShopping\ViewModel\ProShop $viewModel */
    $viewModel = $block->getData('viewModel');
    $categoryList = $viewModel->getAllSystemCategory();

    if($this->isPopupEnabled() && $this->isContactEnabled()){
?>


<script type="text/javascript">
    require(['jquery', // jquery Library

       // Magento text translate (Validation message translte as per language)

        // Jquery Validation Library
        'jquery/ui' // Jquery UI Library
    ], function ($) {
        $('#pop_button').click(function() {
         if($(this).css("margin-left") == "300px" || $(this).css("margin-left") == "280px")
        {
            $('.popup').animate({"margin-left": '-=300'});
            $('#pop_button').animate({"margin-left": '-=280'});
        }
        else
        {
            $('.popup').animate({"margin-left": '+=300'});
            $('#pop_button').animate({"margin-left": '+=280'});
        }
    });

        $('#pop_button-right').click(function() {


        if($(this).css("margin-right") == "300px" || $(this).css("margin-right") == "280px")
        {
            $('.popup-right').animate({"margin-right": '-=300'});
            $('#pop_button-right').animate({"margin-right": '-=280'});
        }
        else
        {
            $('.popup-right').animate({"margin-right": '+=300'});
            $('#pop_button-right').animate({"margin-right": '+=280'});
        }
    });

    });
    function myFunction() {
        var exists = document.getElementById("g-recaptcha-response");

    if(exists == null){
            //alert('not exists');
    }
    else {
        var check = document.getElementById("g-recaptcha-response").value;
       // alert(check);
        if(check=='' || check == null){
            document.getElementById("recaptcha").style.border = "1px solid #ea0e0e";
            return false;
        }
        else{
            document.getElementById("recaptcha").style.border = "none";
            return true;
        }
    }
}

</script>

<div id="leftcontact" <?php if($this->popupposition() == 0) { echo "class=popup"; } else{ echo "class=popup-right"; }?>
     data-value="hide">
<div id="bcontactForm" name="bMyform" class="block contactFormheader"
     style="width:253px;border:solid 0.1px;border-radius:5px;float:left;padding-left:0px;background:white;padding:10px;">

    <div class="category-container">
        <?php foreach ($categoryList->getItems() as $category) { ?>
            <?php if ($category->getParentId()) { ?>
                <p class="category-link" data-category-id="<?php echo $category->getId(); ?>"><?php echo $category->getName(); ?></p>
            <?php } ?>
        <?php } ?>
    </div>

</div>
</div>

<div <?php if($this->popupposition() == 0) {
    echo "class=share_box";
} else { echo "class=share_box-right";
}?>
    <?php if($this->popupposition() == 0) {
        echo "id=pop_button"; }
    else {
        echo "id=pop_button-right";
    }?>>
        <img src="<?php echo $this->getViewFileUrl('Codilar_ProShopping::images/tss-t.png'); ?>">
</div>

<?php } ?>

<style type="text/css">

    #recaptcha {
      display: inline-block;
      position: relative;
    }

    .share_box{
       position:fixed;
        width:40px;

        left: 0px;
        z-index: 1000;
        top: 200px;
        height: 155px;
    }
    .share_box-right{
       position:fixed;
        width:40px;

        right: 0px;
        z-index: 1000;
        top: 200px;
        height: 155px;
    }
    .rc-anchor-normal {
        height: 74px;
        width: 250px;
    }
    .popup{
       position:fixed;
        width:40px;

        left: 5px;
        z-index: 1000;
        top: 100px;
        height: 155px;
        margin-left: -300px;
    }
    .popup-right{
       position:fixed;
        width:40px;

        right: 5px;
        z-index: 1000;
        top: 100px;
        height: 155px;
        margin-right: -65px;
    }
    .contactFormheader{
        width: 253px;
        border: solid 0.1px;
        border-radius: 5px;
        float: left;
        padding-left: 0px;
        background: white;
        padding: 10px;
        height: 65vh;
    }

    .category-link{
        cursor: pointer;
    }

    .category-container {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 15px;
        padding: 10px;
        align-items: stretch;
    }

    .category-link {
        background-color: #656c7d;
        color: white;
        padding: 10px;
        text-align: center;
    }

</style>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        let url = "<?= $viewModel->getProductCategoryUrl() ?>";
        let categoryId;
        jQuery('.category-link').on('click', function () {
            // Get the data-category-id attribute value of the clicked element
            categoryId = $(this).data('category-id');

            console.log(url);
            let products;
            $.ajax({
                url: url,
                type: 'POST',
                dataType: 'json',
                data: { categoryId: categoryId },
                success: function (response) {
                    products = response.output;
                    console.log(JSON.parse(products));
                },
                error: function (err) {
                    console.log(err.Message)
                }
            });
        });
    });
    //console.log(products.id);
    // Attach a click event listener to all elements with the class "category-link"

</script>
